### PR TITLE
Extend user plugin

### PR DESCRIPTION
**Pull request by gibiwatch**
This is the current implementation what I reported in #413. Currently it only shows read-only values, but I intend to proceed to create editable fields and custom types.

I'm open to comments.

Thank you!

### CODE REVIEW

**Comment by billtomczak** [comment]
I like this idea and will discuss with the team here. If accepted, I see a few things I will likely want to restructure. But otherwise, it looks really good. Thank you!

**Comment by billtomczak** [comment]
@gibiwatch - Much as we like the concept, we feel like it would be better to  implement this as an independent user plugin rather than enhancing the core plugin. I would love to see the end result. Would you be willing to set this up as your own repo for us to fork?

**Comment by gibiwatch** [comment]
@billtomczak thank you for your reply, I am not going to set up a separate public repo for this.

I thought it may be interesting for you to integrate this in SimpleRenew core package, if this is not the case I will simply add it to our own private repo as many other custom plugins we have coded.

If I misunderstood and you just want me to code this as a separate plugin (e.g. **/user/simplerenewprofile**) and issue a new PR against your repo, just let me know.

Thank you.

**Comment by billtomczak** [comment]
@gibiwatch whatever you decide is fine with us. The main point is, it isn't something we are going to pursue in house for now. But my current thinking is that if we ever did, we'd do it as an independent plugin/addon. Thanks for keeping us in the loop!

**Pull request closed without merging**
