### PR TITLE
Issue #365

### PR DESCRIPTION
**Pull request by gibiwatch**
See #365 for original issue details.  
Since I am not confident enough to provide a "full" fix (i.e. reload only the user properties required to update ACL), I am proposing a simple workaround instead: with this PR, you will be able to turn off the whole "refresh user at each request" behaviour via component options.

FYI this fix is actually running on our production server.

### CODE REVIEW

**Comment by billtomczak** [comment]
So sorry @gibiwatch! I just released v1.1.16 before I saw this. I will review this asap for next release.

**Comment by billtomczak** [comment]
@gibiwatch -- would you please take a look at 9b2c81b83548d796b664b987182ea57adcee68a7 and test?

I am assuming that the custom properties are following the old Joomla standard for property names ('_' defines a property as non-public) and/or are created as public properties. I believe this patch will fix this problem.

**Comment by gibiwatch** [comment]
@billtomczak can you explain why you don't keep properties starting with "_"? I mean, you already separate the "standard" properties so anything else is a custom property (regardless of how it's named) and according to the purpose of this PR it should be kept.

Apologies if I am missing something obvious here.

**Comment by billtomczak** [comment]
@gibiwatch -- No, you're quite correct. My concern was about possibly overwriting 'protected' properties that weren't actually protected. I should have looked at the J2 code to verify that all the old-style '_' properties were in fact protected. I was distracted by the the getProperties() method which still obeys that convention. I'm now avoiding getProperties() entirely as the distraction that it is.

Thanks!

See ffc86cf5223b3ba3e60d2ced1727af938ac4d73c and  3f3f7f379708d949300bfc5bffb85b69d65e8d32

**Comment by billtomczak** [comment]
@gibiwatch -- do let me know if the patch I'm proposing works for you.

**Comment by gibiwatch** [comment]
Looks fine, I will test as soon as possible but beware it may take a few days. Thank you!

**Comment by gibiwatch** [comment]
I installed v1.1.16 and manually applied the patch introduced in https://github.com/OSTraining/Simplerenew/commit/3f3f7f379708d949300bfc5bffb85b69d65e8d32.

Everything seems to be working fine.

Would you consider proceeding with this PR anyway, so we can always turn it off in case of unexpected incompatibilities?

**Comment by gibiwatch** [comment]
Thank you!

**Pull request merged**
