### PR TITLE
Issue #359 - add edit button in profile view

### PR DESCRIPTION
**Pull request by gibiwatch**
The feature is there.

About the display: I wasn't sure where you'd want to place the link and what class you'd like to apply to it. If you provide some info on that topic, I will update my PR accordingly.

### CODE REVIEW

**Comment by billtomczak** [comment]
Thank you! We'll be reviewing this soon and let you know.

**Comment by gibiwatch** [comment]
Up?

**Comment by billtomczak** [comment]
Please change the target branch for this PR to development and we'll bring this into the release planned for next week.

**Comment by billtomczak** [comment]
@gibiwatch -- nvm - I've merge your PR into the development branch here b20e03490800661ef0e00b9cae446d659cd56e1a.

**Comment by billtomczak** [comment]
This PR was merged into the development and now incorporated into [v1.1.13](https://github.com/OSTraining/Simplerenew/releases/tag/v1.1.13)

**Comment by gibiwatch** [comment]
@billtomczak thank you!

**Pull request closed without merging**
